sudo:required
services:
        -docker
before_install:
        -dockerbuild -t vaishnavi1/docker-react -f Dockerfile.dev .
script:
        -docker run -e CI=true vaishnavi1/docker-react npm run test
