# My first traverse file I  am writing
sudo: required
services:
        - docker
before_install:
        - docker build -t vaishnavi1/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true vaishnavi1/docker-react npm run test
